language: objective-c
compiler: clang
env:
    matrix:
        - NAME="libc++" \
            SCRIPT_PATH="scripts" \
            SCRIPT="$SCRIPT_PATH/build-$NAME.sh"
        - NAME="libstdc++" \
            SCRIPT_PATH="scripts" \
            SCRIPT="$SCRIPT_PATH/build-$NAME.sh"
script:
    "$SCRIPT"
git:
    depth: 10
